### ISSUE TITLE
[Bug]: ADB Bridge not connecting and Bonelab Loading Infinitely on First Startup.

### ISSUE THREAD

**Issue by Crumpet0** [LemonLoader/MelonLoader_057#1]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

On first startup of Bonelab with Lemonloader installed game loads infinitely. Tried using ADB Bridge, would not connect so used standard method instead and downloaded both main and patch .obb files from OculusDB. Tried uninstalling and reinstalling game, repatching Bonelab, restarting headset and reinstalling .obb files. I also could not find a log file. If someone could please help me it would be greatly appreciated. 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Debugging issues like these aren't easy so the workaround is to reinstall BONELAB, copy the obbs onto a PC or something, use standard uninstall after patching, then restore obbs.
