### ISSUE TITLE
[Bug]: Lemonloader chrashes everytime I try to patch an app

### ISSUE THREAD

**Issue by KinetikLite** [LemonLoader/MelonLoader_057#10]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

I try to patch a game and lemonloader just crashes.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Old issue but is the game BONELAB or something else?
