### ISSUE TITLE
[Bug]: Lemon can not be exited cleanly, preferences do not get saved and mods are not deinitialized

### ISSUE THREAD

**Issue by Runner822** [LemonLoader/MelonLoader_057#14]
### Describe the new feature or enhancement

Do you have any plans to have the exact same functionality as MelonLoader in the future?

**Comment by TrevTV** [comment]
As in? Lemon is based on ML 0.5.7 and as such, supports the features in it.
If you mean stuff in 0.6.0, chances are that work won't be done by me and there is still a lot of stuff that isn't Android ready in that release

**Comment by Runner822** [comment]
lemon loader cant save Values

**Comment by TrevTV** [comment]
Just tested, while it did throw some weird error, MelonPreferences was able to write and read the config perfectly fine.

**Comment by Runner822** [comment]
mod values i mean mod setting

**Comment by Runner822** [comment]
gun tweaker

**Comment by Runner822** [comment]
and SpiderQuest

**Comment by TrevTV** [comment]
Confirmed as an issue, will try to make a fix for the next Lemon update

**Comment by Runner822** [comment]
also fusion devs say lemonloader has bugs

**Comment by Runner822** [comment]
thank you!
