### ISSUE TITLE
[Bug]: BONELAB mods like Multiplayer Mockup and BONELAB: Fusion not work

### ISSUE THREAD

**Issue by HeatSavag3** [LemonLoader/MelonLoader_057#15]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting device.

### Describe the issue.

Not gonna be whining or anything, but mods like Quicksilver, Multiplayer Mockup, Fusion, etc. do not work with LemonLoader. Please try to fix this in the next few updates, and thanks. I don't want to rush you so take your time.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by ghost** [comment]
this is not a bug, you simply cannot get steam running on a quest.

**Comment by TrevTV** [comment]
Obviously, Mockup does not work, this is mentioned in the installer. Fusion is in the works with no guarantee.
Other mods are a dupe of #11 and will already be fixed next update
