### ISSUE TITLE
[Enhancement]: Support Unity 2021.3.15

### ISSUE THREAD

**Issue by E4zily** [LemonLoader/MelonLoader_057#18]
### Describe the new feature or enhancement

Self-explanatory by the title: make it support 2021.3.15. Even while it does not say 'unsupported', in the middle of the patching process it goes "java.io.FileNotFoundException: https://lemon.sircoolness.dev/android/2021.3.15.zip".

**Comment by TrevTV** [comment]
I do not host the dependencies and can't add more myself.

**Comment by TrevTV** [comment]
Dependencies can be generated with [UDGB](https://github.com/LemonLoader/UDGB/releases/tag/v1.0.0)
Next installer update will allow you to easily use them for patching, bypassing that error
