### ISSUE TITLE
[Enhancement]: Support for Unity v2018.4.36.7132039

### ISSUE THREAD

**Issue by krulci** [LemonLoader/MelonLoader_057#19]
### Describe the new feature or enhancement

As title.
The game PrincessConnectReDive (TW) uses Unity v2018.4.36.7132039
But it do not show up in Lemon Installer
https://play.google.com/store/apps/details?id=tw.sonet.princessconnect&pli=1

**Comment by TrevTV** [comment]
Issue is due to the game having a custom entry point, will be fixed in the next update
