### ISSUE TITLE
[Bug]: [ERROR] Failed to Invoke Initialize Method!

### ISSUE THREAD

**Issue by krulci** [LemonLoader/MelonLoader_057#21]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

https://codeshare.io/X8xQRz

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Incorrect build files for a unreleased version of Lemon
