### ISSUE TITLE
[Enhancement]: Specify Path of MelonLoader folder

### ISSUE THREAD

**Issue by krulci** [LemonLoader/MelonLoader_057#22]
### Describe the new feature or enhancement

I would like to know which line of code I will have to modify to change the output of the `melonloader` folder, which originally is at `0\Android\data\{packages}\files`
The reason I ask this is because certain emulator has a shared folder that you can access directly with Windows Explorer.
For example with Leidian9, the shared folder is at `mnt\shared\Pictures`.
Which is equivalent to `C:\Users\_\Documents\leidian9\Pictures\` with Windows Explorer.

**Comment by TrevTV** [comment]
Moving stuff like that outside of the app's dedicated data folder will be messy and could lead to permission issues. I would suggest using alternative methods like ADB file transfer (personally I use Sidequest, works for regular android devices too)
