### ISSUE TITLE
[Enhancement]: Update to MelonLoader 0.6.1

### ISSUE THREAD

**Issue by E4zily** [LemonLoader/MelonLoader_057#23]
### Describe the new feature or enhancement

There are many issues in this current version, for example most of the patched Unity apps crash instantly after load, and the last message in the logs is:
`[17:52:37.120] [DEBUG] Return Value = 0`

An update to MelonLoader 0.6.1 should fix most of the issues, and, according to developer's responses on this kind of issue, it will also fix crashing.

https://github.com/LavaGang/MelonLoader/releases/tag/v0.6.1

**Comment by TrevTV** [comment]
Will not be done in this fork, Lemon 0.6.1 will be developed in the main ML repo

Edit note just so it's known: it would require an entire Lemon rewrite to do that, they entirely reworked the Bootstrap and swapped to .NET 6 which messes a lot of stuff up
