### ISSUE TITLE
[Bug]: BONELAB will not load.

### ISSUE THREAD

**Issue by questuserforlife** [LemonLoader/MelonLoader_057#24]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Im writing this on quest so I couldnt drag the file here, but I do have Latest.log . Bonelab will not load at all, I have heavily researched this, and I have found that other people are having the same problem. I waited for an hour several times, other people have waited 7+ hours, I dont know what to do. I have tried downgrading from Bonelab patch 3 to the live patch, still didn't work. Please fix this, I know you really try your best to make Lemonloader the best it can be, so please fix it. I just wanna be Spider-Man in Bonelab. @TrevTV 😁 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
The installer probably didn't save/backup the OBBs, which cause an infinite load. Reinstall Bonelab, backup the files in `Android\obb\com.StressLevelZero.BONELAB`, patch the game, replace those files, start the game

**Comment by questuserforlife** [comment]
I see! There is no OBB for Bonelab after I patched it, your right! But where do I paste the OBB files? In Data? or somewhere else? btw im using CX file explorer.

**Comment by TrevTV** [comment]
In `Android\obb\com.StressLevelZero.BONELAB`

**Comment by questuserforlife** [comment]
Its not there, bonelab isn't in the obb, ill elaborate. I open file explorer, go to main storage, click android, click obb, bonelab is not in the obb, all my other games are though. bonelab is in data though, but it is not in the obb

**Comment by TrevTV** [comment]
Have you reinstalled the game like I said to before

**Comment by questuserforlife** [comment]
yes. i reinstalled it so it was a vanilla game, then went to the obb and copied them, then then i pasted them in my downloads folder so i could access them. then i patched bonelab.

**Comment by questuserforlife** [comment]
wait i copied the files inside the bonelab obb, but do i just copy the entire folder?

**Comment by questuserforlife** [comment]
im going to copy the bonelab obb folder instead of the files in it and see if that works

**Comment by questuserforlife** [comment]
It worked!! thanks so much brother. You make this community very happy, just wanted to let you know. I know your very busy with final exams coming up, but i recommend posting in the discord, or someplace that people can look at and see how to fix it. your a cool guy!

**Comment by manny850** [comment]
@questuserforlife tell me how
