### ISSUE TITLE
BUG LemonLoader for Quest 2 PTC V53?

### ISSUE THREAD

**Issue by questuserforlife** [LemonLoader/MelonLoader_057#25]
when i put the code mods in, the game is super laggy in the loading screen, and i cant load in. i don't want to go back to v51 because if you leave the PTC it does a factory reset, please help. In the latest log it says like, JeviLib [ERROR] or SpiderQuestAPLHA [ERROR]

**Comment by questuserforlife** [comment]
it works i just needed to repatch bonelab

**Comment by TrevTV** [comment]
Lemon works fine on V53 for me

**Comment by questuserforlife** [comment]
https://www.reddit.com/r/BONELAB/comments/12yvop8/help_cant_have_more_than_like_7_mods_only/

**Comment by TrevTV** [comment]
Already known, already fixed and will be part of the next update

**Comment by TrevIsSus** [comment]
sorry to be annoying but can you give a approximate time for when the new update might come out?
