### ISSUE TITLE
[Bug]: Wiped my game save

### ISSUE THREAD

**Issue by iknowwhereyoulive12** [LemonLoader/MelonLoader_057#26]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting device.

### Describe the issue.

I was trying to install LemonLoader but halfway through it said that it didnt work. So I reinstalled bonelab from the quest store [this had happened before with beat saber and bmbf, but i had gotten the save back for beat saber] but my save file and my mods were gone. How can I get them back? WITHOUT using a dev save (i'll feel like i cheated.)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by questuserforlife** [comment]
you cant bro, if u paid any attention, trev said that if u delete bonelab without backing up ur stuff, everything will be gone. just get a dev save, that's ur only hope.

**Comment by iknowwhereyoulive12** [comment]
ok thanks
