### ISSUE TITLE
[Bug]: Bonelab indefinite load on first startup.

### ISSUE THREAD

**Issue by PheilimOB** [LemonLoader/MelonLoader_057#29]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Bonelab, on first launch, loads indefinitely.
I would upload the log file, but it will not process. 
I have been trying for 2 days. I'm exhausted, please help.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by PheilimOB** [comment]
Okay, I'm stupid. The OBBS didn't get backed up. Solved this by restoring Bonelab, copying the restored game's obbs into a folder, patching it again, then pasting them in.
And it's funny because this was said as a resolution to the same issue on this github page. I just was too stupid to understand lol. Do not close this issue please as I want it to stay as a fix for future people suffering the same problem, as people are more likely to look at open issues than closed ones.

**Comment by PheilimOB** [comment]
Leaving this open as a fix for people.

**Comment by TrevTV** [comment]
I'll pin this, better than leaving it open

**Comment by lazarus810** [comment]
I tried doing that and it didn't work. I tried doing it. I use the two OBB files  I waited For minutes It is not Working.
