### ISSUE TITLE
On v55 Lemon Installer breaks 

### ISSUE THREAD

**Issue by Swifter264** [LemonLoader/MelonLoader_057#30]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Ever since I updated to v55 on Quest 2 it broke like when I run the Lemon Installer at start works fine but when I click on an app to patch it just closes like I don't see the patch button or nothing Lemon Installer just closes so I'm just assuming v55 broke it I even reset my headset.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Unable to replicate on v55
