### ISSUE TITLE
[Bug]: Deletes my game and then crashes during install

### ISSUE THREAD

**Issue by linospngn** [LemonLoader/MelonLoader_057#32]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Just crashes after it deletes my game.  Useless program.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by linospngn** [comment]
IT IS SERIOUSLY BROKEN IT WONT EVEN OPEN NOW!!!!!!!!!!!!!!!!!! 🤬

**Comment by TrevTV** [comment]
Unable to replicate, no logs or information provided
