### ISSUE TITLE
[Bug]: Issues with building bootstrap

### ISSUE THREAD

**Issue by Checkerb0ard** [LemonLoader/MelonLoader_057#35]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting device.

### Describe the issue.

When attempting to build the project bootstrap, you continuously get the error "'filesystem' file not found"
The output gives no additional information either making it super difficult to troubleshoot this error.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I've never experienced this and I'm not knowledgeable on compiling C++ so I wouldn't really be able to help much
