### ISSUE TITLE
[Bug]: Bonelab crashes on first startup.

### ISSUE THREAD

**Issue by agent-bono** [LemonLoader/MelonLoader_057#36]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Bonelab crashes on first startup. tried reinstalling and resetting my oculus. nothing helped. can someone help me? I am very new to modding so this is kind confusing for me.
[MelonLoader_23-07-26_09-11-33.599.log](https://github.com/LemonLoader/MelonLoader/files/12168743/MelonLoader_23-07-26_09-11-33.599.log) i found this from the files?
### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
New Lemon update; try reinstalling the game and repatch
