### ISSUE TITLE
[Bug]: crashing when choosing the game i want to patch

### ISSUE THREAD

**Issue by Litheli** [LemonLoader/MelonLoader_057#38]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

this has been a problem ive been experiencing for a while, when i go to pick a game to patch it will crash every time without fail (i have taken a screenshot and put the file down below
![367978710_840001521025093_3205037408866915700_n](https://github.com/LemonLoader/MelonLoader/assets/142359910/c6535e32-7176-43d8-b4b4-fe821d05a399)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
New Lemon update; try updating the installer
