### ISSUE TITLE
[Enhancement]: Linux support

### ISSUE THREAD

**Issue by dim-ghub** [LemonLoader/MelonLoader_057#4]
### Describe the new feature or enhancement

Is there a way to use the ADB bridge with Linux? And if not, will you add support for it?

**Comment by TrevTV** [comment]
Currently, no, but it's possible I could add support for it at some point. If you need a workaround, backing up the data in `Android/data/<package name>` and `Android/data/<package name>`, running the standard install, then restoring that data should work the same.

**Comment by TrevTV** [comment]
Closing in favor of #16
