### ISSUE TITLE
[Bug]: java.io.FileNotFoundException on all games

### ISSUE THREAD

**Issue by Starry-TM** [LemonLoader/MelonLoader_057#45]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Every Game I try to patch any game, it fails on the same error. here is the error:
java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.melonloader.intaller/files/temp/<package name>/dependencies/dex

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
You're running an outdated installer
