### ISSUE TITLE
[Bug]: 09-12 22:55:49.093 I/Zygote ( 774): Process 26037 exited due to signal 9 (Killed)

### ISSUE THREAD

**Issue by ghost** [LemonLoader/MelonLoader_057#46]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

[MelonLoader_23-09-12_22-49-06.404.log](https://github.com/LemonLoader/MelonLoader/files/12591327/MelonLoader_23-09-12_22-49-06.404.log)
Everytime I launch my game it instantly crashes, could anyboyd help?

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I don't support Gorilla Tag
