### ISSUE TITLE
[Bug]: UniverseLib not working in LemonLoader

### ISSUE THREAD

**Issue by ChipLag** [LemonLoader/MelonLoader_057#47]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

When I try to use UnityExplorer in LemonLoader, it seems to not work, which i think could possibly be a UniverseLib issue because it doesnt seem to load at all. I tried many things such as copying UniverseLib to a bunch of different Directories, and even reinstall ing the game, and nothing seems to help. It keeps giving me the same Error in the logs.
[Latest.log](https://github.com/LemonLoader/MelonLoader/files/12640355/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by ChipLag** [comment]
I even tried the following UnityExplorer Versions: 3.3.3,3.3.4,3.3.7,2.0.0,4.0.0
Either it leaded to a Crash (2.0.0) or it gives another Error (3.X.X) about MelonLoader.Tomlyn.Model.TomlObject having an issue with HarmonyInit. 
[Latest.log](https://github.com/LemonLoader/MelonLoader/files/12640393/Latest.log)

I have no idea on what else it could be, since the errors Don't give a lot of information on what exactly Went wrong.

**Comment by TrevTV** [comment]
It looks to be an issue with UE/UL specifically, which makes sense considering that the dev never implemented Lemon support into either tool.
