### ISSUE TITLE
[Bug]: Infinite loading screen

### ISSUE THREAD

**Issue by JacketMiami12** [LemonLoader/MelonLoader_057#48]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

I know several people have had this issue before, and I've tried every fix I could find, but nothing seems to work, everything goes smoothly, I can install the apk and run it perfectly fine, there are no issues when I actually patch it, but upon opening bonelab, the loading screen with the three dots goes on forever, I have waited for up to an hour with no fix, and I also believe that I can hear other menu sounds from the oculus home while the loading screen is up. I have tried the OBB fix, but the OBB's are there even after patching. and replacing them then does not change anything, I have also tried factory resetting my headset to no avail. There was no log file.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I need some kind to log to debug it, try following this and upload what it gives you

Assuming you're on a Windows computer with SideQuest installed and your headset connected to it, you should be able to run the following command in CMD/Terminal, then launch the game. After the game crashes, you should be able to copy all the text (preferably into a text doc) then post it.

`%USERPROFILE%\AppData\Local\Programs\SideQuest\resources\app.asar.unpacked\build\platform-tools\adb.exe logcat -v time MelonLoader:D CRASH:D Mono:W mono:D mono-rt:D Zygote:D A64_HOOK:V DEBUG:D Binder:D AndroidRuntime:D *:S`

**Comment by tbtmre** [comment]
how do i fix this on quest

**Comment by DavidZvo** [comment]
Same thing

**Comment by TrevTV** [comment]
No one has provided additional information, closing.
