### ISSUE TITLE
[Bug]: Boot loop when reinstalling bonelab

### ISSUE THREAD

**Issue by L1TTLECLOWN** [LemonLoader/MelonLoader_057#49]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

I'm asking this for a friend to see if anyone else has had this problem, while I was guiding my friend on how to patch bonelab he was patching bonelab then suddenly his headset started restarting on its own, has anyone had this problem and fixed it?

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
This seems entirely unrelated to Lemon, it does nothing system level that would cause boot loops
