### ISSUE TITLE
[Bug]: ADB bridge not opening

### ISSUE THREAD

**Issue by 6543ozne** [LemonLoader/MelonLoader_057#5]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [x] Tried restarting device.

### Describe the issue.

I am trying to install code mods for bonelab , everything goes smooth but when I try to do the adb bridge thing, the app won't open. I installed .net 6.0 but when i click the app, nothing happens, no window, nothing in the quest, Nothing!

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Old issue but chances are you're missing _some_ dependency. You can try this specific .NET 6 version and see if that fixes it, feel free to reopen this issue if needed
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-windows-x64-installer
