### ISSUE TITLE
[Bug]: Crashing

### ISSUE THREAD

**Issue by TheScriptShowcaser** [LemonLoader/MelonLoader_057#50]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Hello! Im unable to even use the app, after about 2 minutes of the ui loading (lemon installer's ui) it says my headset has lost tracking then it closes

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I don't know why the app would cause tracking issues, the load time depends on however many Unity games you have installed

**Comment by TheScriptShowcaser** [comment]
Didnt mean to close it, i installed 0.11, loads fine now but it keeps failing to patch

**Comment by TrevTV** [comment]
That is because the old installer is completely different and expects a different setup than what the 0.2.0 update provides

**Comment by TheScriptShowcaser** [comment]
I reinstalled 0.2.0 but the crashing is still here and lags my headset

**Comment by TheScriptShowcaser** [comment]
Closing because i made another report
