### ISSUE TITLE
[Bug]: Crashing 

### ISSUE THREAD

**Issue by Zernedd** [LemonLoader/MelonLoader_057#51]
### All of the following criteria must be met

- [x] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Trying to mod Gorilla Tag and The game sends me home on startup. Never had this issue in to other lemon ver just this one.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by KINGCUBING** [comment]
[Latest.log](https://github.com/LemonLoader/MelonLoader/files/12778357/Latest.log)

**Comment by Zernedd** [comment]
[MelonLoader_23-10-01_18-04-52.796.log](https://github.com/LemonLoader/MelonLoader/files/12778360/MelonLoader_23-10-01_18-04-52.796.log)

**Comment by ReZOnGithub** [comment]
skill issue

**Comment by TrevTV** [comment]
I do not support modding Gorilla Tag
