### ISSUE TITLE
[Enhancement]: support apps

### ISSUE THREAD

**Issue by Higor95y** [LemonLoader/MelonLoader_057#52]
### Describe the new feature or enhancement

Could someone tell me which apps it supports because I tested it and it seems that ballons td 6 is not supported :(

**Comment by TrevTV** [comment]
It supports whatever it launches on

**Comment by Higor95y** [comment]
> It supports whatever it launches on

But it only works in VR glasses, right? because I thought it works on Android, but when I go into it it says it doesn't support it...

**Comment by TrevTV** [comment]
Not sure where you read that, I personally use it on non-VR games. It was mainly tested with a VR game, but not built specifically for them.

**Comment by TrevTV** [comment]
Closing due to the non-specific nature of the question
100% application support can't be promised
