### ISSUE TITLE
Failed to Invoke PreStart Method

### ISSUE THREAD

**Issue by 15rf** [LemonLoader/MelonLoader_057#53]
### All of the following criteria must be met

- [x] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the game.
- [x] Tried reinstalling LemonLoader.
- [x] Tried restarting device.

### Describe the issue.

Whenever I patch any game and launch it I stare at the unity loading screen for 5 minutes then crash. Im not using any mods.

Log file:

https://cdn.discordapp.com/attachments/1161174173419323452/1161314143211626546/message.txt?ex=6537d913&is=65256413&hm=be311536f8bc66dbbbb88e7cf177243c5b391c93fef3195c861fb72411dbaad0&

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I need a logcat log to debug this

Assuming you're on a Windows computer with SideQuest installed and your headset connected to it, you should be able to run the following command in CMD/Terminal, then launch the game. After the game crashes, you should be able to copy all the text (preferably into a text doc) then post it.

`%USERPROFILE%\AppData\Local\Programs\SideQuest\resources\app.asar.unpacked\build\platform-tools\adb.exe logcat -v time MelonLoader:D CRASH:D Mono:W mono:D mono-rt:D Zygote:D A64_HOOK:V DEBUG:D Binder:D AndroidRuntime:D *:S`

**Comment by 15rf** [comment]
https://docs.google.com/document/d/1QzZUyP6pQv7B9toucNHdyRKmfHIGbu44rPi3fFJd6x4/edit?usp=sharing

**Comment by TrevTV** [comment]
Your game is too new for Lemon to support it, it may or may not get fixed in the future, I do not know yet

**Comment by 15rf** [comment]
tragic

**Comment by ShiinaRinne** [comment]
Hello~I also encountered an error similar to this issue in `Project Sekai(Unity 2020.3.32f1)`
https://docs.google.com/document/d/14Q750-Xh5y9i_a6VEWhiewYBTgRtb4wyZ7ULSGCbuxQ/edit?usp=sharing

This is the error in this issue:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> 
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

This is the error I encountered:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> 
System.FormatException: Invalid or corrupt metadata (magic number check failed)
```

It appears they are caused by different reasons. Is there a way to fix it?

**Comment by Alphamageddon** [comment]
15rf here (original poster)

The problem with me seemed to be a anticheat could it be the same with you?
