### ISSUE TITLE
[Bug]: Synth Riders fails to start once patched

### ISSUE THREAD

**Issue by KatDevsGames** [LemonLoader/MelonLoader_057#54]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Upon patching Synth Riders, the application fails to start. The application DOES produce the initial logo and a brief loading screen but crashes shortly thereafter.

Cause of crash is not obvious based on logs. See attached:
[Latest.log](https://github.com/LemonLoader/MelonLoader/files/12879844/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Are you able to get a logcat log? That usually provides more information

----

Assuming you're on a Windows computer with SideQuest installed and your headset connected to it, you should be able to run the following command in CMD/Terminal, then launch the game. After the game crashes, you should be able to copy all the text (preferably into a text doc) then post it.

`%USERPROFILE%\AppData\Local\Programs\SideQuest\resources\app.asar.unpacked\build\platform-tools\adb.exe logcat -v time MelonLoader:D CRASH:D Mono:W mono:D mono-rt:D Zygote:D A64_HOOK:V DEBUG:D Binder:D AndroidRuntime:D *:S`

**Comment by KatDevsGames** [comment]
Synth Riders got a MAJOR update just a few hours ago and this problem no longer occurs.
