### ISSUE TITLE
[Bug]: Crash after starting the game

### ISSUE THREAD

**Issue by TianMengLucky** [LemonLoader/MelonLoader_057#55]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [ ] Tried restarting device.

### Describe the issue.

After I tried to patch the game Among Us on Android, when I opened the game it would start with an infinite black screen, with an icon in the upper left corner showing that it was loading, and then crash directly after the black screen ended

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Stripping issue, LemonLoader/MelonLoader#8
