### ISSUE TITLE
keeps crashing while restoreing[Bug]: 

### ISSUE THREAD

**Issue by Whotay** [LemonLoader/MelonLoader_057#56]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

So every time i try to patch a game it says lemon loader not responding.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
What game are you patching?

**Comment by TrevTV** [comment]
No additional information has been given, closing.
