### ISSUE TITLE
[Bug]: EXTREME lag and crashing

### ISSUE THREAD

**Issue by TheScriptShowcaser** [LemonLoader/MelonLoader_057#57]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Basicly, after 2 minutes I get to 1 or 2 fps and then I loose tracking and the app closes itself

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
You mentioned the tracking issue with the installer as well and Lemon vs the installer do entirely different things. Also, Lemon by itself shouldn't cause lag. Sounds like an issue with your headset or the mods you have installed.
