### ISSUE TITLE
[Bug]: "Failed to patch"

### ISSUE THREAD

**Issue by TMPOraryStudios** [LemonLoader/MelonLoader_057#58]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Hello, when i try to patch "Gorilla Tag Horror", i get an error ("java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.melonloader.installer/files/temp/com.Lemmon.GorilllaTagHorror/dependencies/dex").
I've been trying for a while now and it still wont work. Any help?

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Your installer is outdated.
