### ISSUE TITLE
[Bug]: Bone Lib not showing up

### ISSUE THREAD

**Issue by Envixitie** [LemonLoader/MelonLoader_057#60]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

I cant seem to figure out how to get the mods to load I watched a yt video followed all the steps but cant seem to even find bonelib I Put the mods folder of bonelib into the mods folder on my quest and my plugins folder to the plugins folder on my quest and nothing seems to be working

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
You need to provide a log or else I can't do anything

**Comment by TandyTnd** [comment]
I think it has to do with not being able to backup the android.data and android.obb folders
