### ISSUE TITLE
[Bug]: Failed to generate dependency's you may need to generate them yourself

### ISSUE THREAD

**Issue by Alphamageddon** [LemonLoader/MelonLoader_057#61]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

No latest.log for my knowledge.

How to I generate dependency's?

or is the version just un-supported

![image](https://github.com/LemonLoader/MelonLoader/assets/148015878/b96f7af2-1faa-4d46-8800-e3c9cc35e674)
 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
You use [UDGB](https://github.com/LemonLoader/UDGB) then give the generated zip to the installer through the kebab menu.
