### ISSUE TITLE
[Bug]: When I patch my app it opens but after 5 seconds or so it just closes.

### ISSUE THREAD

**Issue by Swifter264** [LemonLoader/MelonLoader_057#64]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

The title. But also I'm on v59 and I have no other accounts on my quest.
[Latest.log](https://github.com/LemonLoader/MelonLoader/files/13255640/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
I don't support Gorilla Tag.

**Comment by Swifter264** [comment]
This happens on another game. I was just trying it on this game.
