### ISSUE TITLE
When I go to lemon installer I get an error that says Unable to connect to GitHub!

### ISSUE THREAD

**Issue by capuchinfan** [LemonLoader/MelonLoader_057#65]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [x] Tried restarting device.

### Describe the issue.

When I enter lemon loader I accept everything and the Github not connected message appears

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Your device can't access GitHub then, you could try going to it in a web browser to check but I can't do much to help.
