### ISSUE TITLE
[Bug]: Failed to Invoke PreStart Method!

### ISSUE THREAD

**Issue by Codewitt** [LemonLoader/MelonLoader_057#69]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

[Latest.log](https://github.com/LemonLoader/MelonLoader/files/13699069/Latest.log)
Patching process completes fine.
Booting the game for the first time results in a blank screen for a few mins till it crashes.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Old issue but likely the game just isn't supported. Lemon isn't a super stable project
