### ISSUE TITLE
[Bug]: lemonloader doesn't open

### ISSUE THREAD

**Issue by R3my010** [LemonLoader/MelonLoader_057#70]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

so, basically when i open lemonloader its just pure black, and if i wait for too long it crashes.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by J-Emil-P** [comment]
Try giving lemon installer storage permission from settings 

I had to wait for around 5 minutes until there was no black screen

**Comment by TrevTV** [comment]
It can take awhile to load depending on what games you have installed.
