### ISSUE TITLE
[Bug]: still not fixed

### ISSUE THREAD

**Issue by TheScriptShowcaser** [LemonLoader/MelonLoader_057#71]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Its me again, please just fix my issue, if you dont remember what it is:
I open it like normal, after 1 minute i get down to 1 fps for a while, my screen becomes black, i loose tracking and when its back to normal the app closes itself

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TheScriptShowcaser** [comment]
Just noticed something, it drains all my memory

**Comment by TrevTV** [comment]
No clue, likely a mod issue as I've seen no one else have that with base Lemon
