### ISSUE TITLE
[Bug]: Quest 3 bug

### ISSUE THREAD

**Issue by Goobertsnoobert** [LemonLoader/MelonLoader_057#72]
### All of the following criteria must be met

- [x] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Whenever you patch BONELAB it shows text saying failed to save data. This makes it so using any code mods on BONELAB is impossible, and as far as I've seen, this is only on quest three. 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Wait for Meta to fix it, or wait for me to maybe possibly do LemonLoader/MelonLoader#7
