### ISSUE TITLE
[Bug]: Patch Failed

### ISSUE THREAD

**Issue by Nuni2203** [LemonLoader/MelonLoader_057#73]
### All of the following criteria must be met

- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

if i try to patch the game after 1 minute it just say *Failed*

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
No additional information provided, can't infer much from that
