### ISSUE TITLE
[Bug]: Error message for Quest 3 making it impossible to use.

### ISSUE THREAD

**Issue by gakaga1** [LemonLoader/MelonLoader_057#74]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

When ever you try to start patching, in the middle of it, it says " Failed to save data". If you choose to continue anyways, the game never loads. There are no fixes that i have found so far, can we please get a fix?

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Wait for Meta to fix it, or wait for me to maybe possibly do LemonLoader/MelonLoader#7
