### ISSUE TITLE
[Bug]: bonelib not showing bone menu on quest 2.

### ISSUE THREAD

**Issue by sewihside** [LemonLoader/MelonLoader_057#76]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

When you install bonelib on the beta version of bonelab the bone menu does not show up in preferences. on top of that none of the code mods work. i don't have a log file because i've uninstalled and reinstalled my bonelab and lemon loader 3 times now. i've also factory reset my oculus and nothing seems to fix the problem. the only "fix" seems to be keeping bonelab in the original version its set at, then code mods work that don't require a gui in the bone menu. im hoping im just stupid and i just haven't found an obvious fix.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Sounds like a mod issue, not a Lemon issue
