### ISSUE TITLE
[Enhancement]: Add a mod template

### ISSUE THREAD

**Issue by bubzilla** [LemonLoader/MelonLoader_057#77]
### Describe the new feature or enhancement

pleasee i want to develop mods for this UwU

**Comment by lightyuwu** [comment]
You should develop mods using MelonLoader for your PC, since mods are Cross-Compatible...
Just follow the instructions from the MelonLoader website.

**Comment by ChipLag** [comment]
Yes, just Like @lightthefox said, you should develop mods on your Computer.
But Quick Info, you might need to copy some DLL's, e.g. InputSystem over, but they should Always be Cross-Compatible.
But some Things are not supported from one version to another, so its recommended to grab a game that has the same unity version on your PC and code for that game, then transfer it over.

**Comment by bubzilla** [comment]
The only issue is there are VR only games which aren't compatible with PCVR like my game for an example.

**Comment by lightyuwu** [comment]
But still, you can just make a mod using your PC and a random MelonLoader DLL, then transfer it to your phone/vr and test it.

**Comment by TrevTV** [comment]
Just follow the MelonWiki as mentioned before. Same exact API
