### ISSUE TITLE
[Bug]: Can't tap use this folder on Quest 3 Android data folder

### ISSUE THREAD

**Issue by ParkerLoney** [LemonLoader/MelonLoader_057#78]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

On Meta Quest 3 v63 LemonLoader does not work due to the Android data folder not available to use. You can't just disable automatic backups in LemonLoader so it is impossible to pass the screen and LemonLoader does not work at all. The following message is said when attempting to select the data folder, "To protect your privacy, choose another folder".

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by LizardGames123** [comment]
I have the same problem here. I was trying to get bonelab fusion for me and my friends and then i had to factory reset the headset which then updated it so now its doing this. I have no idea how to fix it

**Comment by TrevTV** [comment]
Wait for Meta to fix it, or wait for me to maybe possibly do LemonLoader/MelonLoader#7
