### ISSUE TITLE
[Enhancement]: add manual patch from pc

### ISSUE THREAD

**Issue by techERioP** [LemonLoader/MelonLoader_057#80]
### Describe the new feature or enhancement

With the new v63 update you can't acces the android data and obb folder, so why not make a manual patch from pc if everything is moved to java? (Sorry for my bad English, i am italian)

**Comment by Potato644** [comment]
yes please do this.

**Comment by MoonCakeToo** [comment]
agreed if possible

**Comment by portal2707070** [comment]
pls

**Comment by TrevTV** [comment]
Being done with the new installer.
