### ISSUE TITLE
[Bug]: scoped storage 

### ISSUE THREAD

**Issue by arandomperson23** [LemonLoader/MelonLoader_057#82]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the game.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting device.

### Describe the issue.

I am unable to patch any file due to me having to grant permission on using the android file but its blank and the use this folder button is greyed out due to the scoped storage me and everyone using a quest is having a issue with.
I was wondering if there is a way to patch the files from pc ?

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by bingbongitsbing** [comment]
Everyone is having the same issue right now as V63 broke permissions for scoped storage.

One thing I'd like to note is that while many people claim that V64 will fix this issue, I just updated on my Quest 3 and still cannot grant LemonLoader permissions to the data or obb folders.

Like @TrevTV mentioned in his recent enhancement issue, he could add Shizuku support to allow install standalone again, or he could create a standalone installer for windows using something like adb to access the files.

Unfortunately you'll just have to wait, I even tried emulating android and having LemonLoader run on copied files but sadly it just doesn't work at the moment.

**Comment by TrevTV** [comment]
Wait for Meta to fix it, or wait for LemonLoader/MelonLoader#7
A temporary version of the installer that I've attached to the latest release lets you skip those options though if you want to try
