### ISSUE TITLE
[Bug]: Lemon Loader Perm Bypass not working

### ISSUE THREAD

**Issue by Troyydev** [LemonLoader/MelonLoader_057#83]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

so ive used the new Lemon loader perms bypass and it said success when patching and while i open the application (bonelab) it stuck me on 3 dots and my oculus buttons did not worked so i tried gorilla tag (to see if its the game or lemon loader) and it worked again but gorilla tag insta crashed meaning smt when wrong with the signing APK as gtag detect unofficial apks but not lemon loader so whats going on and how can i fix it (in on V64)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by SnoStarA** [comment]
I can confirm that it is not just you. After patching bonelabs, once I opened it, it would infinitely load with 3 dots on the screen. And as you said, when opening bonelabs, the Quest Button would not work at all unless you press it multiple times to get the "Report A Bug" menu.

**Comment by TrevTV** [comment]
![image](https://github.com/LemonLoader/MelonLoader/assets/25110388/7493f8ed-fe38-41b5-a043-87019b45969d)
