### ISSUE TITLE
[MelonLoader Version] : Upgrade to Melonloader v6.1 or later 

### ISSUE THREAD

**Issue by Lightmaxifrvr** [LemonLoader/MelonLoader_057#84]
Like in the title it should be started on moving Lemon Loader to Melonloader V6.1 or above since BONELAB's newest Patch does nto support MelonLoader v0.5.7 on PC anymore and it would cause trouble to have to maintain sepereate versions of the Code Mods

**Comment by oculusguy** [comment]
it isnt supported at all, even on quest

**Comment by TrevTV** [comment]
Actively being worked on in a separate repo, see [LemonLoader/MelonLoader2](https://github.com/LemonLoader/MelonLoader2)

**Comment by JTMC-G3** [comment]
> Actively being worked on in a separate repo, see [LemonLoader/MelonLoader2](https://github.com/LemonLoader/MelonLoader2)

smooch

**Comment by TrevTV** [comment]
Basically done and will probably be releasing soon-ish
