### ISSUE TITLE
[Bug]: Wont Let me Patch a Game.

### ISSUE THREAD

**Issue by RechixAlt** [LemonLoader/MelonLoader_057#87]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [ ] Tried restarting device.

### Describe the issue.

Basiccly when i patch my game is ask if i want to install it, when i click yes it loads and ask me again if i wanna install it, any help?

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
Installer is being rewritten, you can reopen/remake the issue if it occurs once the new installer is released

**Comment by RechixAlt** [comment]
OK thanks, is there a early acces

**Comment by TrevTV** [comment]
No
