### ISSUE TITLE
[Bug]: Cant patch any games, Returns with a 404 server error.

### ISSUE THREAD

**Issue by ForeverBloxian** [LemonLoader/MelonLoader_057#89]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

Cant patch any games, Returns with a 404 server error.
Even after reinstalling, it sill occurs.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
The Unity versions are likely not supported then, or you have a connection issue with either GitHub or sircoolness.dev.
