### ISSUE TITLE
[Enhancement]: ADB Bridge for macOS

### ISSUE THREAD

**Issue by KendrickLamar2003** [LemonLoader/MelonLoader_057#9]
### Describe the new feature or enhancement

So I have an iMac that I use. I also have a Windows Laptop that is usable, but irritating and half-broken. When I used ABD Bridge on Windows, my quest suddenly disconnected, therefore breaking the app and corrupting my BoneLab install. So I would like a version of the bridge for macOS as my iMac is wayyy better than my Windows laptop, and thats being objective.

**Comment by TrevTV** [comment]
Closing in favor of #16
